# .streamlit/config.toml

[theme]
primaryColor = "#1E90FF"           # Dodger Blue
backgroundColor = "#2E2E2E"        # Dark Grey
secondaryBackgroundColor = "#1C1C1C"  # Very Dark Grey
textColor = "#FFFFFF"              # White
font = "sans serif"
